### ISSUE TITLE
ms8607.begin() locks up Adafruit ItsyBitsy nRF52840

### ISSUE THREAD

**Issue by Brezensalzer** [adafruit/Adafruit_MS8607#2]
Hello,

I have a MS8607 module (via Stemma QT) connected to an ItsyBitsy nRF52840. When I upload the example sketch "sensor_test", the ItsyBitsy hangs after the serial message "Adafruit MS8607 test!".  Something weird happens at the ms8607.begin() statement.
While the MS8607 is connected, I can't upload a new sketch to the ItsyBitsy.

- the MS8607 module works fine  with "sensor_test" on a QtPy SAMD21
- the ItsyBitsy nRF52840 works fine with a LSM9DS1 module (via StemmaQT)
- Arduino IDE 1.8.15 with newest board definitions and libraries on Ubuntu 20.04

So it is probably not a hardware issue.

Thanks in advance for any hints!

**Comment by hathach** [comment]
hi @Brezensalzer , I don't have the sensor to do the actual testing. However PR #3 could fix this issue. Would you mind testing the latest code from master branch ? If it does not help, I will try to get the sensor for hand-on testing.

**Comment by Brezensalzer** [comment]
Hi @hathach,
I can confirm that PR #3 does fix the issue for me.
Thank You for Your fast response!

**Comment by ladyada** [comment]
ok great, we will be adding -Werror for return type to our board def to avoid this issue going forward

**Comment by hathach** [comment]
glad that it works out for you, this issue is indeed very annoying. 

- https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/711
- https://github.com/adafruit/ArduinoCore-samd/pull/315

will force it into error instead of warnings.
