### ISSUE TITLE
Re-initialization of the sensor causing heap memory growth

### ISSUE THREAD

**Issue by gmanrc** [adafruit/Adafruit_MS8607#4]
I'm using this Adafruit sensor and library for a sensor node development.
One of the requirements is for the node to have extensive battery life, and I am optimizing battery life by using watchdog.sleep on the micro-controller, as well as cutting power to the sensors.
As a result, I have to re-initialize the sensor every time it wakes up. My problem is that the initialization appears to be cause memory leak, and the heap stack is growing. Eventually, there is no more free memory available and the node crashes.
I have other sensors that do not cause loss of free memory due to re-initialization. 
Is there anything that can be done in the initialization code?

**Comment by ladyada** [comment]
are you deleting the object? allocated memory is freed there
https://github.com/adafruit/Adafruit_MS8607/blob/master/Adafruit_MS8607.cpp#L71

**Comment by gmanrc** [comment]
Hi @ladyada , Thank you for your rapid response! Can you clarify further what I would need to call out to delete the object?
I'm sorry, I am very new to this. But am learning quickly thanks to the resources you provide!
I tried calling this: ms8607.~Adafruit_MS8607(); out but ended up getting this error: 

CORRUPT HEAP: Bad head at 0x3ffb8444. Expected 0xabba1234 got 0x3ffb84e4
15:05:42.332 -> abort() was called at PC 0x40083b99 on core 1
15:05:42.332 -> 
15:05:42.332 -> ELF file SHA256: 0000000000000000
15:05:42.332 -> 
15:05:42.332 -> Backtrace: 0x400857f0:0x3ffb1a90 0x40085a65:0x3ffb1ab0 0x40083b99:0x3ffb1ad0 0x40083cc5:0x3ffb1b00 0x400d91bb:0x3ffb1b20 0x400d56d5:0x3ffb1de0 0x400d5670:0x3ffb1e30 0x4008a101:0x3ffb1e60 0x40081dee:0x3ffb1e80 0x40083a91:0x3ffb1ea0 0x4000bec7:0x3ffb1ec0 0x400e79f9:0x3ffb1ee0 0x400d1a2f:0x3ffb1f00 0x400d0e73:0x3ffb1f20 0x400d3b4d:0x3ffb1fb0 0x40086a75:0x3ffb1fd0
15:05:42.377 -> 
15:05:42.377 -> Rebooting...

**Comment by caternuson** [comment]
`As a result, I have to re-initialize the sensor every time it wakes up.`
Are you creating a new instance each time you come out of sleep? Or just calling begin() again?

You generally don't call the destructor directly. It's called automatically when the code, or code block, exits.

It sounds like your code is not exiting when it goes to sleep and then creates new instances each time it wakes up. Somehow check for that when you wake up and don't do it. Just reuse the existing instance. And call begin() to "re-initialize" the sensor.

**Comment by gmanrc** [comment]
Thank you for your response @caternuson.

So, by "re-intialize" I do mean ms8607.begin() every time, because if I do not call begin again, then I just get zero's for the data. This is because I turn off the sensors to save power. When I don't turn off the sensors, and only initialize (begin()) once, it does continue to work with a single initialization, but the power consumption is obviously high and constant.

How do I exit? Or what do I need to check specifically in the library to see a previous instance?

**Comment by caternuson** [comment]
Can you provide full example code? Linking to it is fine.

It may be these?
```
  temp_sensor = new Adafruit_MS8607_Temp(this);
  pressure_sensor = new Adafruit_MS8607_Pressure(this);
  humidity_sensor = new Adafruit_MS8607_Humidity(this);
```

**Comment by gmanrc** [comment]
Here is the base of my code; it is simply modified version of the example code Sensor_Test.ino.
My main difference is that I've brought what was in the setup loop into the main loop as you'll see, so that I can reinitialize it after turning off each loop.
My D2 pin that I am triggering high and low is for turning on and off the sensor. 
The final line, is to see the available Free memory on my ESP32. But I also have this same setup on an M0 featherboard express that I can run; but I don't have yet an easy command to monitor the free memory as its running.


#include <Arduino.h>

// Basic demo for reading Humidity and Temperature
#include <Wire.h>
#include <Adafruit_MS8607.h>
#include <Adafruit_Sensor.h>

Adafruit_MS8607 ms8607;
void setup(void) {
  Serial.begin(115200);
 // while (!Serial) delay(10);     // will pause Zero, Leonardo, etc until serial console opens
  pinMode(D2, OUTPUT);// voltage regulator // remove these two lines normally
  
  Serial.println("Adafruit MS8607 test!");
  
}

void loop() {
  digitalWrite(D2,HIGH);
  delay(500);

// Try to initialize!
  ms8607.begin();
  if (!ms8607.begin()) {
    Serial.println("Failed to find MS8607 chip");
    while (1) { delay(10); }
  }
  Serial.println("MS8607 Found!");

  ms8607.setHumidityResolution(MS8607_HUMIDITY_RESOLUTION_OSR_8b);
  Serial.print("Humidity resolution set to ");
  switch (ms8607.getHumidityResolution()){
    case MS8607_HUMIDITY_RESOLUTION_OSR_12b: Serial.println("12-bit"); break;
    case MS8607_HUMIDITY_RESOLUTION_OSR_11b: Serial.println("11-bit"); break;
    case MS8607_HUMIDITY_RESOLUTION_OSR_10b: Serial.println("10-bit"); break;
    case MS8607_HUMIDITY_RESOLUTION_OSR_8b: Serial.println("8-bit"); break;
  }
  // ms8607.setPressureResolution(MS8607_PRESSURE_RESOLUTION_OSR_4096);
  Serial.print("Pressure and Temperature resolution set to ");
  switch (ms8607.getPressureResolution()){
    case MS8607_PRESSURE_RESOLUTION_OSR_256: Serial.println("256"); break;
    case MS8607_PRESSURE_RESOLUTION_OSR_512: Serial.println("512"); break;
    case MS8607_PRESSURE_RESOLUTION_OSR_1024: Serial.println("1024"); break;
    case MS8607_PRESSURE_RESOLUTION_OSR_2048: Serial.println("2048"); break;
    case MS8607_PRESSURE_RESOLUTION_OSR_4096: Serial.println("4096"); break;
    case MS8607_PRESSURE_RESOLUTION_OSR_8192: Serial.println("8192"); break;
  }
  Serial.println("");

    sensors_event_t temp, pressure, humidity;
    ms8607.getEvent(&pressure, &temp, &humidity);
    Serial.print("Temperature: ");Serial.print(temp.temperature); Serial.println(" degrees C");
    Serial.print("Pressure: ");Serial.print(pressure.pressure); Serial.println(" hPa");
    Serial.print("Humidity: ");Serial.print(humidity.relative_humidity); Serial.println(" %rH");
    Serial.println("");

    delay(2000);
    digitalWrite(D2,LOW);
    Serial.print("Free:"); Serial.println(ESP.getFreeHeap());
}

**Comment by caternuson** [comment]
Try calling `reset()` and `init()` in the loop instead of `begin()`. Move `begin()` back to start.

**Comment by gmanrc** [comment]
> Try calling `reset()` and `init()` in the loop instead of `begin()`. Move `begin()` back to start.

The init() function is requesting a int32_t sensor_id. What is that? It won't compile without it

**Comment by ladyada** [comment]
pass in any number

**Comment by gmanrc** [comment]
Thank you @ladyada and @caternuson. It appears to be working now. The memory is not creeping up anymore after every power-on of the sensors.
I will now try it with my other ICM20948 sensor that I was experiencing a similar issue.
